name: Update database

on:
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: download
      run: |
        yarn install
        make update
        make test
    - name: publish-git
      run: |
        bash commit_database.sh
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
