name: Update database

on:
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: install
      run: yarn install
      env:
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: download
      run: make update
    - name: test
      run: make test
    - name: publish
      run: |
        bash commit_database.sh
      env:
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
